#enable splash text rendering over the wallpaper
splash = false

#fully disable ipc
# ipc = off

wallpaper {
    monitor = eDP-2
    path = ~/pictures/cyber-building.jpg
  }

wallpaper {
    monitor = DP-6
    path = ~/pictures/cyberpunk-blue-city.jpg
  }

wallpaper {
    monitor = DP-4
    path = ~/pictures/cyberbridge.jpg
  }

wallpaper {
    monitor = DP-5
    path = ~/pictures/cybercat.jpg
  }

