#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

exec-once = $status_bar
exec-once = $wallpaper_manager
exec-once = $network_manager
exec-once = $clipboard_manager_daemon
exec-once = hyprpm reload

exec = gsettings set org.gnome.desktop.interface color-scheme "$gtk4_theme"
exec = gsettings set org.gnome.desktop.interface gtk-theme "$gtk3_theme"
exec = hyprctl setcursor "WinSur Dark Cursors" 24
