################
### MONITORS ###
################

# See https://wiki.hypr.land/Configuring/Monitors/
monitorv2 {
  output = DP-5
  mode = 1920x1080@60
  position = 0x0
  scale = 1
  transform = 0
}
monitorv2 {
  output = DP-6
  mode = 1920x1200@60
  position = 1920x0
  scale = 1
  transform = 0
}
monitorv2 {
  output = DP-4
  mode = 1920x1080@60
  position = 3840x0
  scale = 1
  transform = 0
}
monitorv2 {
  output = eDP-2
  mode = 1920x1200@60
  position = 5760x0
  scale = 1
  transform = 0
}

