###################
### MY PROGRAMS ###
###################

# See https://wiki.hypr.land/Configuring/Keywords/
$browser = librewolf
$chat_client = element-desktop
$clipboard_manager_daemon = clipcatd # used with quickshell launcher (clipboard mode)
$edit_screenshot_script = ~/.config/hypr/scripts/edit_last_screenshot.sh
$launcher = quickshell
$launcher_script = ~/.config/hypr/scripts/launcher.sh $launcher
$music_player = feishin
$network_manager = nm-applet
$screenshot_tool = hyprshot -m region -o ~/screenies
$status_bar = quickshell # ~/.config/quickshell/shell.qml
$terminal = alacritty
$toggle_layout_script = ~/.config/hypr/scripts/toggle_layout.sh
$wallpaper_manager = hyprpaper # ~/.config/hypr/hyprpaper.conf
$window_control_script = ~/.config/hypr/scripts/window_control.sh

#############################
### ENVIRONMENT VARIABLES ###
#############################

# See https://wiki.hypr.land/Configuring/Environment-variables/

env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24

##############
### OTHERS ###
##############
$gtk4_theme = "prefer-dark"
$gtk3_theme = "Arc-Darkest-Strawberry"
$bluetooth_headphones_id = # your bluetooth headphones MAC address
