##############################
### WINDOWS AND WORKSPACES ###
##############################
# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

# Ignore maximize requests from apps. You'll probably like this.
windowrule = suppress_event maximize, match:class .*

# Fix some dragging issues with XWayland
windowrule = match:focus false, match:class ^$, match:title ^$,match:xwayland true,match:float 1,match:fullscreen false,match:pin false

workspace = 1, monitor:DP-5, persistent:true
workspace = 2, monitor:DP-6, default:true, persistent:true
workspace = 3, monitor:DP-4, persistent:true
workspace = 4, monitor:eDP-2 persistent:true
workspace = special:code, on-created-empty:$terminal
workspace = special:magic, on-created-empty:$terminal

