;==========================================================
;
;
;   ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;   ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
;   ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
;   ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
;   ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║
;   ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
;
;
;   To learn more about how to configure Polybar
;   go to https://github.com/polybar/polybar
;
;   The README contains a lot of information
;
;==========================================================

include-file = ~/.config/polybar/modules/i3
include-file = ~/.config/polybar/modules/pulseaudio-control-output
include-file = ~/.config/polybar/modules/date
include-file = ~/.config/polybar/modules/spotify
include-file = ~/.config/polybar/variables/colors

[bar/example]
width = 100%
height = 24pt
line-size = 3pt
radius = 0 
scroll-up = "#i3.prev"
scroll-down = "#i3.next"
tray-position = right

background = ${colors.background}
foreground = ${colors.foreground}


border-size = 0pt
border-color = #000000

padding-left = 1
padding-right = 1

module-margin = 1 

font-0 = JetBrainsMonoNL Nerd Font;2
modules-left = spotify

modules-center = i3 
modules-right = pulseaudio-control-output xkeyboard time battery

cursor-click = pointer

enable-ipc = true

bottom = false

wm-restack = i3

; override-redirect = true
[bar/monitor1-2]
inherit = bar/example
monitor = DP1-2

[bar/monitor1-1]
inherit = bar/example
monitor = DP1-3


[settings]
screenchange-reload = true
pseudo-transparency = true

